language: objective-c
osx_image: xcode10.2

branches:
  only:
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N

script:
  - set -o pipefail
  - cd Example
  - pod install 
  - xcodebuild test -enableCodeCoverage YES -workspace ViperMcFlurry.xcworkspace -scheme ViperMcFlurry-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
